spring.application.name=lec25

server.port=${PORT:8085}

spring.thymeleaf.cache=false
spring.main.allow-bean-definition-overriding=true

spring.data.mongodb.uri=mongodb+srv://4723:${MONGODB_PASSWORD}@jeongmin.xveq2tp.mongodb.net/tacoclouddb
